server:
  port: 8081
  servlet:
    context-path: /luckmoney

limit:
  minMoney: 0.01
  maxMoney: 200
  description: minmum money is ${limit.minMoney} yuan maxmum money is ${limit.maxMoney} yuan

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckymoney
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
